
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vabjoqckbtoqqmbpvggb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhYmpvcWNrYnRvcXFtYnB2Z2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NTAxMTUsImV4cCI6MjA1NzIyNjExNX0.a6Txof1VX9sk4Y9_L03oPYSzL7vTnfjTY1ntigyd8u0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
